# Generated by Django 4.0.5 on 2022-06-21 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('air_quality', models.CharField(max_length=10, verbose_name='Air Quality')),
                ('pm_2point5', models.CharField(max_length=10, verbose_name='PM 2.5')),
                ('pm_10', models.CharField(max_length=10, verbose_name='PM 10')),
                ('no_2', models.CharField(max_length=10, verbose_name='NO2')),
                ('o_3', models.CharField(max_length=10, verbose_name='O3')),
                ('co', models.CharField(max_length=10, verbose_name='CO')),
                ('so_2', models.CharField(max_length=10, verbose_name='SO2')),
                ('temperature', models.CharField(max_length=10, verbose_name='Temprature')),
                ('humidity', models.CharField(max_length=10, verbose_name='Humidity')),
                ('wind_speed', models.CharField(max_length=10, verbose_name='Wind Speed')),
                ('uv', models.CharField(max_length=10, verbose_name='UV')),
                ('checked_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
