# Generated by Django 4.0.5 on 2022-06-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airreport',
            name='air_quality',
            field=models.CharField(max_length=100, verbose_name='Air Quality'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='co',
            field=models.CharField(max_length=100, verbose_name='CO'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='humidity',
            field=models.CharField(max_length=100, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='no_2',
            field=models.CharField(max_length=100, verbose_name='NO2'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='o_3',
            field=models.CharField(max_length=100, verbose_name='O3'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='pm_10',
            field=models.CharField(max_length=100, verbose_name='PM 10'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='pm_2point5',
            field=models.CharField(max_length=100, verbose_name='PM 2.5'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='so_2',
            field=models.CharField(max_length=100, verbose_name='SO2'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='temperature',
            field=models.CharField(max_length=100, verbose_name='Temprature'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='uv',
            field=models.CharField(max_length=100, verbose_name='UV'),
        ),
        migrations.AlterField(
            model_name='airreport',
            name='wind_speed',
            field=models.CharField(max_length=100, verbose_name='Wind Speed'),
        ),
    ]
